import { Job } from "@/types";

export const mockJobs: Job[] = [
  {
    id: "job_1",
    title: "Thiết kế UI/UX cho Web3 dApp (DeFi)",
    description: "Cần tìm chuyên gia UI/UX có kinh nghiệm làm các dự án Web3, DeFi. Giao diện tối màu, hỗ trợ mobile responsive tốt, ưu tiên dùng Figma. Ứng viên cần show portfolio các dự án crypto đã làm.",
    budget: 500.0,
    duration: "1-3 tháng",
    deadline: "2026-07-15T00:00:00Z",
    skills: ["Figma", "UI/UX", "Web3", "Tailwind CSS"],
    status: "OPEN",
    clientId: "client_1",
    clientName: "DefiLabs Inc",
    applicationCount: 5,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), // 2 days ago
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "job_2",
    title: "Viết Smart Contract cho NFT Marketplace",
    description: "Cần dev kinh nghiệm viết Smart Contract bằng Solidity/Aiken (Cardano) cho dự án NFT Marketplace mới. Yêu cầu viết test cẩn thận (coverage >90%).",
    budget: 1500.5,
    duration: "> 3 tháng",
    deadline: "2026-08-01T00:00:00Z",
    skills: ["Solidity", "Smart Contract", "Aiken", "Testing"],
    status: "OPEN",
    clientId: "client_2",
    clientName: "NFT Ocean",
    applicationCount: 12,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), // 5 days ago
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "job_3",
    title: "Tối ưu hóa SEO cho website",
    description: "Cần chuyên gia SEO để audit và tối ưu hóa website của chúng tôi để lọt top 1 Google search với các từ khóa liên quan đến dịch vụ Freelance.",
    budget: 300.0,
    duration: "< 1 tháng",
    deadline: "2026-06-30T00:00:00Z",
    skills: ["SEO", "Marketing", "Google Analytics", "Content Writing"],
    status: "OPEN",
    clientId: "client_3",
    clientName: "SEO Master",
    applicationCount: 2,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), // 1 day ago
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "job_4",
    title: "Xây dựng Landing Page React.js",
    description: "Cần một bạn Frontend Dev code landing page dựa trên design Figma có sẵn. Yêu cầu làm đúng pixel-perfect, có animation nhẹ nhàng (Framer Motion).",
    budget: 250.0,
    duration: "< 1 tháng",
    deadline: "2026-07-05T00:00:00Z",
    skills: ["React.js", "Tailwind CSS", "Framer Motion", "Figma"],
    status: "OPEN",
    clientId: "client_4",
    clientName: "Startup Hub",
    applicationCount: 8,
    createdAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(), // 10 hours ago
    updatedAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "job_5",
    title: "Phát triển Mobile App (React Native)",
    description: "Dự án phát triển ứng dụng mobile cho sàn thương mại điện tử. Đã có sẵn backend APIs. Yêu cầu code sạch, dễ maintain.",
    budget: 1200.0,
    duration: "1-3 tháng",
    deadline: "2026-07-20T00:00:00Z",
    skills: ["React Native", "TypeScript", "Redux", "Mobile Development"],
    status: "OPEN",
    clientId: "client_1",
    clientName: "DefiLabs Inc",
    applicationCount: 1,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(), // 7 days ago
    updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "job_6",
    title: "Dịch thuật Anh - Việt cho Bạch thư (Whitepaper)",
    description: "Cần dịch một đoạn Whitepaper dài 30 trang từ tiếng Anh sang tiếng Việt. Yêu cầu am hiểu thuật ngữ Crypto/Blockchain để dịch chuẩn xác.",
    budget: 150.0,
    duration: "< 1 tháng",
    deadline: "2026-06-25T00:00:00Z",
    skills: ["Translation", "English", "Vietnamese", "Blockchain"],
    status: "OPEN",
    clientId: "client_5",
    clientName: "Crypto Global",
    applicationCount: 15,
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(), // 14 days ago
    updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "job_7",
    title: "Backend Engineer (NestJS / PostgreSQL)",
    description: "Team đang cần gấp 1 Backend Dev mạnh NestJS để support làm tính năng Chat Realtime (Socket.io) và tối ưu database queries.",
    budget: 800.0,
    duration: "1-3 tháng",
    deadline: "2026-07-10T00:00:00Z",
    skills: ["NestJS", "Node.js", "PostgreSQL", "Socket.io", "Redis"],
    status: "OPEN",
    clientId: "client_6",
    clientName: "Tech Startup",
    applicationCount: 4,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), // 3 days ago
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "job_8",
    title: "Tạo Model 3D cho Game Metaverse",
    description: "Cần artist vẽ và tạo model 3D cho các nhân vật trong game vũ trụ (phong cách low-poly). Sẽ có test năng lực trước khi chốt.",
    budget: 2000.0,
    duration: "> 3 tháng",
    deadline: "2026-08-15T00:00:00Z",
    skills: ["3D Modeling", "Blender", "Game Art", "Unity"],
    status: "OPEN",
    clientId: "client_7",
    clientName: "Metaverse Gaming",
    applicationCount: 0,
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(), // 1 hour ago
    updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "job_9",
    title: "Cộng tác viên Content Writer (Tech Blog)",
    description: "Cần tìm người viết bài chuẩn SEO cho blog công nghệ (chủ đề AI, Blockchain, Web3). Trả lương theo từng bài. Lịch viết đều đặn 2 bài/tuần.",
    budget: 100.0,
    duration: "1-3 tháng",
    deadline: "2026-06-28T00:00:00Z",
    skills: ["Content Writing", "Copywriting", "Tech Blog", "SEO"],
    status: "OPEN",
    clientId: "client_8",
    clientName: "Web3 News",
    applicationCount: 9,
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(), // 6 days ago
    updatedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "job_10",
    title: "Kiểm thử bảo mật (Penetration Testing)",
    description: "Thuê chuyên gia an ninh mạng pentest cho sàn giao dịch DEX. Cần report chi tiết về các lỗ hổng tìm được và cách khắc phục.",
    budget: 3000.0,
    duration: "< 1 tháng",
    deadline: "2026-07-01T00:00:00Z",
    skills: ["Cybersecurity", "Penetration Testing", "Audit", "DeFi"],
    status: "OPEN",
    clientId: "client_9",
    clientName: "DEX Secure",
    applicationCount: 3,
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(), // 4 days ago
    updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  }
];
